// ── Shared ATS data constants ─────────────────────────────────────────────
//
// These constants are consumed by both `atsKeywords.js` (for keyword
// suggestion and analysis helpers) and `atsScoring.js` (for the canonical
// scoring algorithm). They live in this leaf module — rather than inside
// either consumer — so that neither has to import from the other. That is
// required because `atsKeywords.calculateATSScore` delegates to
// `atsScoring.calculateDetailedScore`; if the shared data stayed in
// `atsKeywords.js`, the imports would form a cycle.
//
// No logic belongs in this file. If a constant needs a helper function to
// be used, the helper belongs in the consumer that needs it, not here.

// ── Industry Keywords ─────────────────────────────────────────────────────

export const industryKeywords = {
  technology: [
    'JavaScript',
    'Python',
    'Java',
    'C++',
    'C#',
    'TypeScript',
    'Go',
    'Rust',
    'React',
    'Angular',
    'Vue',
    'Node.js',
    'Express',
    'Django',
    'Flask',
    'AWS',
    'Azure',
    'GCP',
    'Docker',
    'Kubernetes',
    'CI/CD',
    'DevOps',
    'SQL',
    'MongoDB',
    'PostgreSQL',
    'Redis',
    'Microservices',
    'REST API',
    'GraphQL',
    'Agile',
    'Scrum',
    'Git',
    'Linux',
    'System Design',
    'Cloud Computing',
    'Machine Learning',
    'AI',
    'Data Science',
    'TensorFlow',
    'PyTorch',
    'Pandas',
    'NumPy',
    'Scikit-learn',
    'Big Data',
    'Hadoop',
    'Spark',
    'Kafka',
    'Elasticsearch',
    'Terraform',
    'Ansible',
    'Jenkins',
    'GitHub Actions',
  ],
  marketing: [
    'SEO',
    'SEM',
    'Social Media',
    'Content Marketing',
    'Email Marketing',
    'Google Analytics',
    'PPC',
    'CRM',
    'Marketing Automation',
    'Brand Strategy',
    'Market Research',
    'Digital Advertising',
    'Campaign Management',
    'Copywriting',
    'Lead Generation',
    'B2B Marketing',
    'B2C Marketing',
    'Growth Hacking',
    'Marketing Analytics',
    'Conversion Optimization',
    'A/B Testing',
    'Inbound Marketing',
    'Outbound Marketing',
    'Marketing Funnel',
    'Customer Acquisition',
    'Retention Marketing',
    'Brand Management',
  ],
  finance: [
    'Financial Analysis',
    'Budgeting',
    'Forecasting',
    'Risk Management',
    'Investment',
    'Portfolio Management',
    'Excel',
    'Bloomberg',
    'SAP',
    'Financial Modeling',
    'Auditing',
    'Tax Planning',
    'Valuation',
    'M&A',
    'Financial Reporting',
    'Compliance',
    'Regulatory Reporting',
    'Corporate Finance',
    'Equity Research',
    'Debt Financing',
    'Cash Flow Management',
    'Financial Strategy',
    'Due Diligence',
  ],
  healthcare: [
    'Patient Care',
    'EMR',
    'HIPAA',
    'Clinical Research',
    'Healthcare Management',
    'Medical Terminology',
    'Patient Safety',
    'Healthcare Compliance',
    'Epic Systems',
    'Nursing',
    'Diagnosis',
    'Treatment Planning',
    'Public Health',
    'Healthcare Administration',
    'Health Informatics',
    'Medical Records',
    'Clinical Documentation',
    'Healthcare Analytics',
    'Population Health',
    'Patient Experience',
    'Quality Improvement',
    'Healthcare Regulations',
  ],
  sales: [
    'Business Development',
    'Account Management',
    'Lead Generation',
    'B2B Sales',
    'B2C Sales',
    'Negotiation',
    'CRM',
    'Salesforce',
    'Pipeline Management',
    'Revenue Growth',
    'Market Expansion',
    'Cold Calling',
    'Consultative Selling',
    'Sales Strategy',
    'Client Relationships',
    'Prospecting',
    'Closing',
    'Sales Analytics',
    'Quota Achievement',
    'Customer Success',
  ],
  education: [
    'Curriculum Development',
    'Classroom Management',
    'Lesson Planning',
    'Student Assessment',
    'Special Education',
    'Educational Technology',
    'Teaching',
    'Instructional Design',
    'E-Learning',
    'Distance Learning',
    'Educational Leadership',
    'Student Engagement',
    'Differentiated Instruction',
    'Learning Management Systems',
    'Academic Advising',
    'Assessment Design',
    'Professional Development',
    'Educational Research',
  ],
  engineering: [
    'CAD',
    'SolidWorks',
    'AutoCAD',
    'MATLAB',
    'Simulink',
    'FEA',
    'CFD',
    'Mechanical Design',
    'Electrical Engineering',
    'Civil Engineering',
    'Structural Analysis',
    'Thermodynamics',
    'Manufacturing',
    'Quality Control',
    'Six Sigma',
    'Lean Manufacturing',
    'PLC',
    'Robotics',
    'Automation',
    'HVAC',
    'Project Engineering',
    'Systems Engineering',
    'Product Design',
  ],
  design: [
    'UI/UX',
    'Figma',
    'Sketch',
    'Adobe XD',
    'Photoshop',
    'Illustrator',
    'Wireframing',
    'Prototyping',
    'User Research',
    'Usability Testing',
    'Design Systems',
    'Visual Design',
    'Interaction Design',
    'Product Design',
    'Graphic Design',
    'Motion Design',
    'Branding',
    'Typography',
    'User Flows',
    'Design Thinking',
    'Responsive Design',
    'Accessibility',
  ],
  consulting: [
    'Strategy Consulting',
    'Management Consulting',
    'Business Analysis',
    'Process Improvement',
    'Change Management',
    'Stakeholder Management',
    'Client Relations',
    'Problem Solving',
    'Data Analysis',
    'Presentation Skills',
    'Business Strategy',
    'Operational Excellence',
    'Digital Transformation',
    'Project Management',
    'Market Analysis',
    'Competitive Strategy',
  ],
  general: [
    'Communication',
    'Leadership',
    'Teamwork',
    'Problem Solving',
    'Time Management',
    'Project Management',
    'Critical Thinking',
    'Analytical Skills',
    'Organization',
    'Attention to Detail',
    'Adaptability',
    'Creativity',
    'Initiative',
    'Reliability',
    'Collaboration',
    'Decision Making',
    'Conflict Resolution',
    'Emotional Intelligence',
    'Strategic Planning',
    'Continuous Improvement',
    'Mentoring',
  ],
};

// ── Action Verbs ──────────────────────────────────────────────────────────

export const actionVerbs = {
  leadership: [
    'Led',
    'Managed',
    'Directed',
    'Supervised',
    'Coordinated',
    'Spearheaded',
    'Orchestrated',
    'Headed',
    'Guided',
    'Mentored',
    'Trained',
    'Delegated',
    'Oversaw',
    'Chaired',
    'Facilitated',
  ],
  achievement: [
    'Achieved',
    'Increased',
    'Decreased',
    'Improved',
    'Reduced',
    'Generated',
    'Delivered',
    'Exceeded',
    'Surpassed',
    'Boosted',
    'Maximized',
    'Optimized',
    'Accomplished',
    'Attained',
    'Realized',
  ],
  development: [
    'Developed',
    'Created',
    'Designed',
    'Built',
    'Implemented',
    'Launched',
    'Established',
    'Founded',
    'Engineered',
    'Architected',
    'Crafted',
    'Formulated',
    'Devised',
    'Pioneered',
    'Innovated',
  ],
  analysis: [
    'Analyzed',
    'Evaluated',
    'Assessed',
    'Researched',
    'Investigated',
    'Identified',
    'Reviewed',
    'Audited',
    'Examined',
    'Scrutinized',
    'Interpreted',
    'Diagnosed',
    'Forecasted',
    'Projected',
    'Measured',
  ],
  collaboration: [
    'Collaborated',
    'Partnered',
    'Facilitated',
    'Negotiated',
    'Communicated',
    'Presented',
    'Advised',
    'Consulted',
    'Liaised',
    'Coordinated',
    'Mediated',
    'Networked',
    'United',
    'Allied',
  ],
  optimization: [
    'Optimized',
    'Streamlined',
    'Enhanced',
    'Automated',
    'Restructured',
    'Revitalized',
    'Transformed',
    'Modernized',
    'Refined',
    'Upgraded',
    'Overhauled',
    'Reorganized',
    'Simplified',
    'Consolidated',
    'Integrated',
  ],
};

// ── Passive Voice Phrases ────────────────────────────────────────────────

// Note: two entries (`'was responsible for'`, `'was in charge of'`) appear
// twice. The duplication is preserved verbatim from the previous module so
// that no consumer's behavior changes; if the list is ever iterated with a
// count-sensitive loop, deduplication must be a deliberate, reviewed change.

export const passivePhrases = [
  'was responsible for',
  'was tasked with',
  'was in charge of',
  'was involved in',
  'was assigned to',
  'was selected to',
  'was given the opportunity to',
  'was able to',
  'was asked to',
  'was required to',
  'was expected to',
  'was supposed to',
  'was responsible for',
  'was in charge of',
  'was part of',
];
